import { useEffect, useState, type FormEvent } from "react";
import { Save, X } from "lucide-react";
import type { DailyOperationalLog } from "../../types";

type Day = DailyOperationalLog["day"];
interface OperationalLogFormProps { isOpen: boolean; onClose: () => void; weeklyLogs: DailyOperationalLog[]; onSave: (log: DailyOperationalLog) => void; }
const days: Day[] = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
const fields = ["sales", "waste", "hours", "productionTarget", "productionMade", "tazaki", "sysco", "bulza", "sticker", "others"] as const;
type Field = (typeof fields)[number];
export function OperationalLogForm({ isOpen, onClose, weeklyLogs, onSave }: OperationalLogFormProps) {
  const [day, setDay] = useState<Day>("Sun");
  const [date, setDate] = useState("2026-06-21");
  const [values, setValues] = useState<Record<Field, string>>({ sales: "14820", waste: "412.50", hours: "124", productionTarget: "11500", productionMade: "11240", tazaki: "4890", sysco: "1100", bulza: "820", sticker: "240", others: "380" });
  const [supplierName, setSupplierName] = useState<DailyOperationalLog["supplierName"]>("Others");
  useEffect(() => { const log = weeklyLogs.find(item => item.day === day); if (!log) return; setDate(log.date); setSupplierName(log.supplierName); setValues({ sales: String(log.sales), waste: String(log.waste), hours: String(log.hours), productionTarget: String(log.productionTarget), productionMade: String(log.productionMade), tazaki: String(log.cogs.tazaki), sysco: String(log.cogs.sysco), bulza: String(log.cogs.bulza), sticker: String(log.cogs.sticker), others: String(log.cogs.others) }); }, [day, weeklyLogs]);
  if (!isOpen) return null;
  const update = (field: Field, value: string) => setValues(current => ({ ...current, [field]: value }));
  const submit = (event: FormEvent) => { event.preventDefault(); onSave({ day, date, supplierName, sales: Number(values.sales) || 0, waste: Number(values.waste) || 0, hours: Number(values.hours) || 0, productionTarget: Number(values.productionTarget) || 0, productionMade: Number(values.productionMade) || 0, cogs: { tazaki: Number(values.tazaki) || 0, sysco: Number(values.sysco) || 0, bulza: Number(values.bulza) || 0, sticker: Number(values.sticker) || 0, others: Number(values.others) || 0 } }); onClose(); };
  const inputClass = "mt-1 w-full rounded-lg border border-zinc-200 bg-white px-3 py-2 text-sm text-zinc-900 outline-none focus:border-orange-500 dark:border-zinc-700 dark:bg-zinc-900 dark:text-white";
  return <div className="fixed inset-0 z-50 flex justify-end bg-black/50 p-0 sm:p-4" role="dialog" aria-modal="true" aria-labelledby="operational-log-title"><form onSubmit={submit} className="flex h-full w-full max-w-2xl flex-col overflow-y-auto bg-zinc-50 p-6 shadow-2xl dark:bg-zinc-950 sm:rounded-3xl"><div className="flex items-start justify-between border-b border-zinc-200 pb-5 dark:border-zinc-800"><div><p className="text-[10px] font-mono font-bold uppercase tracking-widest text-orange-500">Data entry</p><h2 id="operational-log-title" className="mt-1 text-2xl font-black text-zinc-900 dark:text-white">Log daily figures</h2><p className="mt-1 text-xs text-zinc-500">Save operational and COGS figures for one audited day.</p></div><button type="button" onClick={onClose} className="rounded-lg p-2 text-zinc-500 hover:bg-zinc-200 dark:hover:bg-zinc-800" aria-label="Close data entry"><X className="h-5 w-5" /></button></div><div className="grid gap-4 py-5 sm:grid-cols-2"><label className="text-xs font-bold text-zinc-600 dark:text-zinc-300">Day<select className={inputClass} value={day} onChange={e => setDay(e.target.value as Day)}>{days.map(item => <option key={item}>{item}</option>)}</select></label><label className="text-xs font-bold text-zinc-600 dark:text-zinc-300">Date<input className={inputClass} type="date" value={date} onChange={e => setDate(e.target.value)} /></label>{fields.slice(0, 5).map(field => <label key={field} className="text-xs font-bold capitalize text-zinc-600 dark:text-zinc-300">{field.replace(/([A-Z])/g, " $1")}<input className={inputClass} type="number" min="0" step="any" value={values[field]} onChange={e => update(field, e.target.value)} /></label>)}</div><div className="border-t border-zinc-200 py-5 dark:border-zinc-800"><h3 className="text-sm font-black text-zinc-900 dark:text-white">COGS suppliers</h3><div className="mt-3 grid gap-4 sm:grid-cols-2">{fields.slice(5).map(field => <label key={field} className="text-xs font-bold capitalize text-zinc-600 dark:text-zinc-300">{field}<input className={inputClass} type="number" min="0" step="any" value={values[field]} onChange={e => update(field, e.target.value)} /></label>)}<label className="text-xs font-bold text-zinc-600 dark:text-zinc-300">Primary supplier<select className={inputClass} value={supplierName} onChange={e => setSupplierName(e.target.value as DailyOperationalLog["supplierName"])}>{["Tazaki", "Sysco", "Bulza", "Sticker", "Others"].map(item => <option key={item}>{item}</option>)}</select></label></div></div><div className="mt-auto flex justify-end gap-3 border-t border-zinc-200 pt-5 dark:border-zinc-800"><button type="button" onClick={onClose} className="rounded-xl px-4 py-2 text-sm font-bold text-zinc-600 dark:text-zinc-300">Cancel</button><button className="inline-flex items-center gap-2 rounded-xl bg-orange-500 px-4 py-2 text-sm font-bold text-white hover:bg-orange-600"><Save className="h-4 w-4" />Save figures</button></div></form></div>;
}
