name: Add To GitHub projects
description: Automatically add issues and PRs to GitHub projects
author: GitHub
branding:
  icon: table
  color: white
inputs:
  project-url:
    required: true
    description: URL of the project to add issues to
  github-token:
    required: true
    description: A GitHub personal access token with write access to the project
  labeled:
    required: false
    description: A comma-separated list of labels to use as a filter for issue to be added
  label-operator:
    required: false
    description: The behavior of the labels filter, AND to match all labels, OR to match any label, NOT to exclude any listed label (default is OR)
outputs:
  itemId:
    description: The ID of the item that was added to the project
runs:
  using: 'node24'
  main: 'dist/index.js'
  
  name: Add bugs to bugs project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@RELEASE_VERSION
        with:
          # You can target a project in a different organization
          # to the issue
          project-url: https://github.com/orgs/<orgName>/projects/<projectNumber>
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: bug, needs-triage
          label-operator: OR

        name: Adds all issues that don't include the 'bug' or 'needs-triage' labels to project board

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@RELEASE_VERSION
        with:
          project-url: https://github.com/orgs/<orgName>/projects/<projectNumber>
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: bug, needs-triage
          label-operator: NOT
